FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Controllers/BeneficiarioController.cs
using FI.AtividadeEntrevista.BLL;
using FI.AtividadeEntrevista.DML;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAtividadeEntrevista.Models;

namespace WebAtividadeEntrevista.Controllers
{
    public class BeneficiarioController : Controller
    {
        // GET: Beneficiario
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Incluir(BeneficiarioModel model)
        {
            BoBeneficiario bo = new BoBeneficiario();

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {

                if (bo.VerificarExistencia(model.CPF))
                {
                    return Json("CPF já cadastrado!");
                }
                else
                {
                    return Json("Beneficiario inserido com sucesso");
                }
            }
        }

        public ActionResult ConfirmarCPF(BeneficiarioModel model)
        {
            BoBeneficiario bo = new BoBeneficiario();

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {

                if (bo.VerificarExistencia(model.CPF))
                {
                    return Json("CPF já cadastrado!");
                }
                else
                {
                    return Json("Beneficiario inserido com sucesso");
                }
            }
        }

        [HttpPost]
        public JsonResult BeneficiarioList(int clienteID, int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                int qtd = 0;
                string campo = string.Empty;
                string crescente = string.Empty;
                string[] array = jtSorting.Split(' ');

                if (array.Length > 0)
                    campo = array[0];

                if (array.Length > 1)
                    crescente = array[1];

                List<Beneficiario> beneficiarios = new BoBeneficiario().Listar(clienteID);
                //List<Beneficiario> beneficiarios = new BoBeneficiario().Pesquisa(jtStartIndex, jtPageSize, campo, crescente.Equals("ASC", StringComparison.InvariantCultureIgnoreCase), out qtd);

                //Return result to jTable
                return Json(new { Result = "OK", Records = beneficiarios, TotalRecordCount = qtd });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Beneficiario/Index.cshtml
@{
//Layout = null;
}

@section scripts{
    
    <script>
        //var urlGet = '@Url.Action("Index", "Beneficiario", new { area = "" })';
        var urlPost = '@Url.Action("Incluir", "Beneficiario", new { area = "" })';
        var urlAlteracao = '@Url.Action("Alterar", "Beneficiario", new { area = "" })';
        var urlBeneficiarioList = '@Url.Action("BeneficiarioList", "Beneficiario", new { area = "" })';
    </script>
    @Scripts.Render("~/bundles/beneficiarios")

}

<form id="formCadastroBeneficiario" method="get">
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="nome">cpf:</label>
                <input required="required" type="text" class="form-control" id="beneficiarioCpf" name="beneficiarioCpf" placeholder="ex.: 010.011.111-00" maxlength="50">
            </div>
        </div>
        <div class="col-md-6">
            <div>
                <label for="sobrenome">nome:</label>
                <input required="required" type="text" class="form-control" id="beneficiarioNome" name="beneficiarioCpfNome" placeholder="ex.: da silva" maxlength="255">
            </div>
        </div>
        <div class="col-md-2">
            <button style="margin-top: 24px; height: 32px;" type="button" id="SendBeneficiario" class="btn btn-sm btn-success">incluir</button>
        </div>
        <hr style="width: 85%;">
        @* Lista de beneficiários *@
        <table id="gridBeneficiarios" class="table"></table>
    </div>
</form>